### ISSUE TITLE
Cannot find module 'async-await-mutex-lock' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by chrisspiegl** [malhotra-sidharth/async-await-mutex-lock#15]
I am using this package in a Nuxt3 application and it showed this error when I was following the readme:

```
Cannot find module 'async-await-mutex-lock' or its corresponding type declarations.ts(2307)
```

I was able to work around this by doing the import the following way:

```js
import { Lock } from 'async-await-mutex-lock/dist'
```

This way, the import appears to work and does not show the error message.

I think this is because the package is not declaring the `exports` in the `pacakge.json`?

**Comment by muffintoad** [comment]
Please provide steps to reproduce the issue if it's still occurring. You can also try mitigate using [skipLibCheck](https://dev.to/imomaliev/til-fix-ts2307-cannot-find-module-src-or-its-corresponding-type-declarations-40n9) in `tsconfig.json`
Closing the issue.
