### ISSUE TITLE
Comparision with similar libraries?

### ISSUE THREAD

**Issue by shner-elmo** [malhotra-sidharth/async-await-mutex-lock#21]
Hey, your package seems pretty neat. How does it compare to `async-lock` and `async-mutex`?
Seems like it offers the same functionality, not sure whats different, and how the performance is

**Comment by muffintoad** [comment]
IMO, comparisons depend on the problem you are trying to solve so it's something the engineers need to work on. Closing this as this isn't a library issue.

**Comment by shner-elmo** [comment]
It's more of an opportunity for you as the package developer to explain whats the difference and why people should be using your package rather than something else. Just my two cents.
