### ISSUE TITLE
Enhancement: possibility to create create a Lock instance with existing 'acquired' inside

### ISSUE THREAD

**Issue by paztis** [malhotra-sidharth/async-await-mutex-lock#22]
I heavily use this library in my code to manage mutex.
There's just one missing case: I have a class where I want to lock some access until it finishes its initialisation

The problem is that lock.acquire is asynchronous and I cannot place it in the constructor.
Is it possible to enhance your library to create a already acquired Lock ?

Like this
```
export declare class Lock<T> {
    constructor(acquired?: boolean, acquiredMap?: Map<string, boolean>)
    private _isAcquired;
    private _acquiredMap;
    private waitingMap;
    private waitingList;
    acquire(key?: T): Promise<void>;
    isAcquired(key?: T): boolean;
    release(key?: T): void;
}
```

with this enhancement I can create an already locked mutex and release it at the end of my initialisation

**Comment by muffintoad** [comment]
Thanks for the suggestion. I am not sure if I fully understand what you mean by "I want to lock some access until it finishes its initialisation". However, you can hold the lock using this library in your class constructor as described here: https://stackoverflow.com/a/50885340

Something like this (P.S I haven't tested the code):

```javascript
class YourClass {
  constructor() {
    return (async () => {

      // Acquire lock here
      await lock.acquire();;
       
      try {
        // Don't return a promise here as Promise may resolve after finally
        // has executed
        // your class initialization steps
      } finally {
        lock.release();
        // Constructors return `this` implicitly, but this is an IIFE, so
        // return `this` explicitly (else we'd return an empty object).
        return this;
      }
    })();
  }
}

// To initialize use await
let classInstance = await new YouClass();
```

Closing this issue as this can be solved without updating the library.

**Comment by paztis** [comment]
This is just running the lock in background

If I do something like this for example

const instance = new MyClockedClass();
await instance.lockedMethod();

In this case I will call the mocked method before the locker is created I
think

Le mer. 13 nov. 2024, 01:18, Sidharth Malhotra ***@***.***> a
écrit :
